services:
  app:
    build:
      context: .
      dockerfile: src/app/Dockerfile
    container_name: ml_app
    env_file:
      - .env
    volumes:
      - ./src:/src/src
    depends_on:
      rabbitmq:
        condition: service_healthy
      database:
        condition: service_started

  web-proxy:
    image: nginx:1.29.0
    container_name: ml_nginx
    depends_on:
      - app
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro

  rabbitmq:
    image: rabbitmq:4.1.2-management
    container_name: ml_rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - rabbitdata:/var/lib/rabbitmq
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "rabbitmq-diagnostics -q ping || exit 1"]
      interval: 5s
      timeout: 4s
      retries: 20
      start_period: 10s
    restart: unless-stopped

  database:
    image: postgres:16
    container_name: ml_postgres
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data

  bot:
    build:
      context: ./src/app/bot
      dockerfile: Dockerfile
    env_file: .env
    depends_on:
      - app

  worker:
    build:
      context: .
      dockerfile: src/app/Dockerfile
    command: python -m src.app.worker.worker
    volumes:
      - ./src:/src/src
    depends_on:
      rabbitmq:
        condition: service_healthy
    env_file:
      - .env
    restart: unless-stopped
    scale: 3

  init-db:
    build:
      context: .
      dockerfile: src/app/Dockerfile
    env_file:
      - .env
    command: python -m src.app.init_db
    volumes:
      - ./src:/src/src
    depends_on:
      - database
      - rabbitmq

  tests:
    build:
      context: .
      dockerfile: src/app/Dockerfile
    env_file:
      - .env
    command: pytest -q -ra
    volumes:
      - ./src:/src/src
    depends_on:
      - database
      - rabbitmq
      - app
      - worker

volumes:
  pgdata:
  rabbitdata: