services:
  app:
    build:
      context: ./src/app
    container_name: ml_app
    env_file:
      - .env
    volumes:
      - ./src/app:/app
    depends_on:
      - database
      - rabbitmq

  web-proxy:
    image: nginx:1.29.0
    container_name: ml_nginx
    depends_on:
      - app
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro

  rabbitmq:
    image: rabbitmq:4.1.2
    container_name: ml_rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - rabbitdata:/var/lib/rabbitmq
    restart: on-failure

  database:
    image: postgres:16
    container_name: ml_postgres
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
  rabbitdata: